### ISSUE TITLE
Remover Usuário incompleto

### ISSUE THREAD

**Issue by guilherme-campagnoli** [guilherme-campagnoli/ProjetoGCS#1]
Não foi implementado a função de remover usuário.

**Comment by guilherme-campagnoli** [comment]
Adicionar o código:

        System.out.println("Usuário removido com sucesso!");
        System.out.println("");

**Comment by laisrosamacedo** [comment]
Bug corrigido. Integrado na master

**Comment by guilherme-campagnoli** [comment]
Teste de regressão passou!!
