### ISSUE TITLE
Corrigir Erros do SonarLint

### ISSUE THREAD

**Issue by guilherme-campagnoli** [guilherme-campagnoli/ProjetoGCS#2]
Standard outputs should not be used directly to log anything
System.out.println("My Message");  // Noncompliant

Compliant Solution
logger.log("My Message");

**Comment by guilherme-campagnoli** [comment]
código modificado.

**Comment by guilherme-campagnoli** [comment]
integrado na master

**Comment by laisrosamacedo** [comment]
Ótimo trabalho

**Comment by laisrosamacedo** [comment]
Testado. Ok
